# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: ansible-playbook -i inv.yml win_ping.yml --vault-password-file VAULT_PASSWORD_FILE
  env:
#    vault_password_file: $(ansible_vault)
    VAULT_PASSWORD_FILE: '$(System.DefaultWorkingDirectory)/vault_password.txt'
  displayName: 'check connectivity'
