---
- name: Create users in linux & windows os
  hosts: "{{ machine }}"
  vars_prompt:
      - name: machine
        prompt: "Please mention on which OS machines you want to add user: \n 1. windows \n 2. linux "
        private: no
      - name: u_item
        prompt: Please mention user name which you want to create on remote servers
        private: no
      - name: p_item
        prompt: Please mention password for the user
        private: yes
      - name: g_item
        prompt: Please mention group name to which you want to add your user 
        private: no
  tasks:
      - name: Import linux add user playbook
        include_tasks: add_user.yml
        when: machine == "linux"
      - name: Import windows add user playbook
        include_tasks: win_add_user.yml
        when: machine == "windows"