---
- name: Create directories in linux & windows OS
  hosts: "{{ machine }}"
  vars_prompt:
    - name: machine
      prompt: "Please mention on which OS machines you want to create directories: \n 1. windows \n 2. linux \n"
      private: no
    - name: directories
      prompt: Please mention directories with comma separated which you want to create on remote servers
      private: no
    - name: u_item
      prompt: Please mention user ownership for directories
      private: no
    - name: g_item
      prompt: Please mention group ownership for directories
      private: no
  tasks:
    - name: Import linux create directories playbook
      include_tasks: directories.yml
      when: machine == "linux"
    - name: Import windows create directories playbook
      include_tasks: win_directories.yml
      when: machine == "windows"