---
      - name: ensure installation directory created for Java
        file:
          path: "{{ java_target_dir }}"
          state: directory
          group: "{{ g_item }}"
          owner: "{{ u_item }}"
          recurse: true
        become: yes 
      - name: Download Java 11
        get_url:
          url: "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz"
          dest: /tmp
          mode: 0755
          group: "{{ g_item }}"
          owner: "{{ u_item }}"
        become: yes
      - name: Unarchive a file downloaded file to "{{ java_target_dir }}"
        unarchive:
          src: "/tmp/jdk-21_linux-x64_bin.tar.gz"
          dest: "{{ java_target_dir }}"
          remote_src: yes
        become: yes
      - name: set JAVA_HOME env variables
        blockinfile:
          path: /etc/profile
          block: | 
              export JAVA_HOME="{{ java_target_dir }}/jdk-21"
              export PATH="$PATH:$JAVA_HOME/bin"
        become: yes
      - name: ensure installation directory created for Tomcat
        file:
          path: "{{tomcat_target_dir}}"
          state: directory
          group: "{{ g_item }}"
          owner: "{{ u_item }}"
        become: yes
      - name: Download Apache Tomcat
        get_url:
          url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.11/bin/apache-tomcat-10.0.11.tar.gz
          dest: /tmp/apache-tomcat-10.0.11.tar.gz
          mode: 0755
          group: "{{ g_item }}"
          owner: "{{ u_item }}"
        become: yes
        
      - name: Extract Apache Tomcat
        unarchive:
          src: /tmp/apache-tomcat-10.0.11.tar.gz
          dest: "{{ tomcat_target_dir }}"
          remote_src: yes
        become: yes
        
      - name: create tomcat service file
        become: yes
        copy:
          dest: /etc/systemd/system/tomcat.service
          content: |-
            [Unit]
            Description=Tomcat Service
            After=network.target

            [Service]
            Type=forking
            User=root
            Environment=JAVA_HOME={{ java_target_dir }}/jdk-21
            ExecStart=/bin/bash {{tomcat_target_dir}}/apache-tomcat-10.0.11/bin/startup.sh
            ExecStop=/bin/bash {{tomcat_target_dir}}/apache-tomcat-10.0.11/bin/shutdown.sh
            Restart=on-abnormal

            [Install]
            WantedBy=multi-user.target

      - name: Enable tomcat service & start
        become: yes
        systemd:
          name: tomcat
          enabled: yes
          state: restarted
          daemon-reload: yes

      - name: change {{tomcat_target_dir}} permission to user {{ u_item }} & group {{ g_item }}
        ansible.builtin.file:
          path: "{{tomcat_target_dir}}"
          group: "{{ g_item }}"
          owner: "{{ u_item }}"
          recurse: yes
        become: yes
      - name: Install ACL package
        ansible.builtin.apt:
          name: acl
          state: present
        become: yes
      - name: Sets default ACL for {{ u_item }} on {{tomcat_target_dir}}
        ansible.posix.acl:
          path: "{{tomcat_target_dir}}"
          entity: "{{ u_item }}"
          etype: user
          permissions: rwx
          default: true
          state: present
          recurse: yes
        become: yes