---
- name: Open ports in NSG
  hosts: linux
  gather_facts: no
  become: yes
  tasks:
    - name: Open ports in NSG
      azure_rm_securitygroup_rule:
            name: Allow ports
            protocol: Tcp
            source_port_range: "*"
            destination_port_range: 8084
            priority: 1001
            direction: Inbound
            access: Allow
            source_address_prefix: "*"
