---
- name: Install and Configure Java and Apache Tomcat on Windows
  hosts: windows
  become_method: pwsh
  tasks:
    - name: Install Java
      win_chocolatey:
        name: openjdk8
        state: present
    - name: Download Apache Tomcat
      win_get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80-windows-x64.zip
        dest: D:\tomcat.zip
    - name: Stop Apache Tomcat Service
      win_service:
        name: Tomcat9
        state: stopped
      ignore_errors: yes
    - name: Extract Apache Tomcat
      win_unzip:
        src: D:\tomcat.zip
        dest: D:\Program Files
    - name: Set Tomcat Environment Variables for CATALINA_HOME
      win_environment:
        name: CATALINA_HOME
        state: present
        value: D:\Program Files\apache-tomcat-9.0.80
        level: machine
    - name: Set Tomcat Environment Variables for JAVA_HOME
      win_environment:
        name: JAVA_HOME
        state: present
        value: C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot
        level: machine
    - name: Check if Tomcat service exists
      win_shell: Get-Service -Name Tomcat9
      register: tomcat_service_info
      ignore_errors: yes

    - name: Install Apache Tomcat Service if not exists
      win_shell: |
        Set-Location -Path "D:\Program Files\apache-tomcat-9.0.80\bin"
        .\service.bat install
      when: tomcat_service_info.rc != 0  # Install only if the service doesn't exist
    - name: Start Apache Tomcat Service
      win_service:
        name: Tomcat9
        start_mode: auto
        state: started
    - name: Check Tomcat URL
      win_uri:
        url: http://172.178.19.181:8080/
