---
- name: Change "Group Ownership" of a Directory in Windows
  hosts: windows
  become_method: pwsh
  vars_prompt:
    - name: target_dir
      prompt: enter directories with comma separated which you want to create on remote vms
      private: no
    - name: g_item
      prompt: enter group ownership who will manage these directories
      private: no
  tasks:
    - name: Add New Group to Directory ACL
      win_acl:
        path: "{{ item }}"
        user: "{{ g_item }}"
        rights: "full_control" 
        state: present
      with_items: "{{ target_dir.split(',') }}"