---
- name: Create directories with correct ownership and permissions
  hosts: windows
  become_method: pwsh

  vars_prompt:
    - name: directories
      prompt: enter directories comma separated
      private: no
    - name: u_item
      prompt: enter owner for directories
      private: no

  tasks:
    - name: Create directories
      win_file:
        path: "{{ item }}"
        state: directory
      with_items: "{{ directories.split(',') }}"
    - name: Change owner of path
      win_owner:
        path: "{{ item }}"
        user: "{{ u_item }}"
        recurse: true
      with_items: "{{ directories.split(',') }}"
